### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Ezinox** [Muqsit/InvCrashFix#13]
can you uptade please ?

**Comment by Muqsit** [comment]
What should the update contain?

**Comment by Ezinox** [comment]
update to 4.0.0

**Comment by Muqsit** [comment]
There's already support for 4.0

**Comment by justauser001** [comment]
Update it to pm5

**Comment by Muqsit** [comment]
This plugin is no longer required since PocketMine v4.4.1
https://github.com/Muqsit/InvCrashFix/blob/api-4.0/README.md

**Comment by Muqsit** [comment]
You may uninstall this plugin and remove it from your plugin's dependency list.
