### ISSUE TITLE
I mean, this was

### ISSUE THREAD

**Issue by Arata-Tempest** [Muqsit/InvCrashFix#4]
I mean, put a page like this in Pocketmine
![Screenshot_2020-10-01-12-44-55](https://user-images.githubusercontent.com/71513892/94791544-a922f780-03e4-11eb-957c-5a788b84af01.png)

**Comment by Arata-Tempest** [comment]
for download

**Comment by Muqsit** [comment]
It is already on poggit. https://poggit.pmmp.io/ci/Muqsit/InvCrashFix
