### ISSUE TITLE
😐

### ISSUE THREAD

**Issue by Arata-Tempest** [Muqsit/InvCrashFix#5]
Why do not you understand? I do not mean just put the download link
I mean, the page is exactly like this, please, please
https://poggit.pmmp.io/p/PlayerVaults/3.2.3
The plugin is in the releases section
Just like the PlayerVaults plugin

**Comment by Muqsit** [comment]
I don't release plugins that fix issue with the game. InvCrashFix and FormImagesFix are too network dependent and can break anytime. This is only a temporary solution until mojang themselves address it.
