### ISSUE TITLE
Crash on API 4.0

### ISSUE THREAD

**Issue by xxFLORII** [Muqsit/InvCrashFix#9]
Error: Call to undefined method pocketmine\event\server\DataPacketSendEvent::setCancelled()
File: /home/mcpe/global_plugins/InvCrashFix_dev-2 (1).phar/src/muqsit/invcrashfix/libs/muqsit/simplepackethandler/interceptor/PacketInterceptorListener
Line: 104
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: InvCrashFix v0.0.1

Code:
[95] 								if(!$handler($packet, $target)){
[96] 									unset($remaining_targets[$i]);
[97] 									break;
[98] 								}
[99] 							}
[100] 						}
[101] 
[102] 						$remaining_targets_c = count($remaining_targets);
[103] 						if($remaining_targets_c !== count($original_targets)){
[104] 							$event->setCancelled();
[105] 							if($remaining_targets_c > 0){
[106] 								$new_target_players = [];
[107] 								foreach($remaining_targets as $new_target){
[108] 									$new_target_player = $new_target->getPlayer();
[109] 									if($new_target_player !== null){
[110] 										$new_target_players[] = $new_target_player;
[111] 									}
[112] 								}
[113] 								Server::getInstance()->broadcastPackets($new_target_players, $packets);
[114] 							}

Backtrace:
#0 pmsrc/src/event/RegisteredListener(75): muqsit\invcrashfix\libs\muqsit\simplepackethandler\interceptor\PacketInterceptorListener->muqsit\invcrashfix\libs\muqsit\simplepackethandler\interceptor\{closure}(object pocketmine\event\server\DataPacketSendEvent)
#1 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent)
#2 pmsrc/src/network/mcpe/NetworkSession(419): pocketmine\event\Event->call()
#3 pmsrc/src/network/mcpe/InventoryManager(162): pocketmine\network\mcpe\NetworkSession->sendDataPacket(object pocketmine\network\mcpe\protocol\ContainerClosePacket)
#4 pmsrc/src/player/Player(2321): pocketmine\network\mcpe\InventoryManager->onCurrentWindowRemove()
#5 plugins/BedWarsPM/src/Bedwars/Bedwars/EventListener/ChestListener(57): pocketmine\player\Player->removeCurrentWindow()
#6 plugins/BedWarsPM/src/muqsit/invmenu/InvMenu(156): Bedwars\Bedwars\EventListener\ChestListener->onSelect(object Core\Core\CorePlayer, object pocketmine\item\ItemBlock, object pocketmine\item\ItemBlock, object pocketmine\inventory\transaction\action\SlotChangeAction, object pocketmine\inventory\transaction\InventoryTransaction)
#7 plugins/BedWarsPM/src/muqsit/invmenu/InvMenuEventHandler(97): muqsit\invmenu\InvMenu->handleInventoryTransaction(object Core\Core\CorePlayer, object pocketmine\item\ItemBlock, object pocketmine\item\ItemBlock, object pocketmine\inventory\transaction\action\SlotChangeAction, object pocketmine\inventory\transaction\InventoryTransaction)
#8 pmsrc/src/event/RegisteredListener(75): muqsit\invmenu\InvMenuEventHandler->onInventoryTransaction(object pocketmine\event\inventory\InventoryTransactionEvent)
#9 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\inventory\InventoryTransactionEvent)
#10 pmsrc/src/inventory/transaction/InventoryTransaction(294): pocketmine\event\Event->call()
#11 pmsrc/src/inventory/transaction/InventoryTransaction(312): pocketmine\inventory\transaction\InventoryTransaction->callExecuteEvent()
#12 pmsrc/src/network/mcpe/handler/InGamePacketHandler(330): pocketmine\inventory\transaction\InventoryTransaction->execute()
#13 pmsrc/src/network/mcpe/handler/InGamePacketHandler(222): pocketmine\network\mcpe\handler\InGamePacketHandler->handleNormalTransaction(object pocketmine\network\mcpe\protocol\types\inventory\NormalTransactionData)
#14 pmsrc/src/network/mcpe/protocol/InventoryTransactionPacket(106): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
#15 pmsrc/src/network/mcpe/NetworkSession(401): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler)
#16 pmsrc/src/network/mcpe/NetworkSession(360): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
#17 pmsrc/src/network/mcpe/raklib/RakLibInterface(186): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[87] [.(...........p,....F...f....x...D ....bgH.,..I..`a.K.M.a8....'.....C...t.....$.)
#18 pmsrc/vendor/pocketmine/raklib/src/server/ipc/RakLibToUserThreadMessageReceiver(43): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[88] .[.(...........p,....F...f....x...D ....bgH.,..I..`a.K.M.a8....'.....C...t.....$)
#19 pmsrc/src/network/mcpe/raklib/RakLibInterface(121): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface)
#20 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#21 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
#22 pmsrc/src/Server(1578): pocketmine\snooze\SleeperHandler->sleepUntil(double 1618011204.2965)
#23 pmsrc/src/Server(1128): pocketmine\Server->tickProcessor()
#24 pmsrc/src/PocketMine(276): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[40] /home/mcpe/CloudServer/servers/BW-2x1-1/, string[48] /home/mcpe/CloudServer/servers/BW-2x1-1/plugins/)
#25 pmsrc/src/PocketMine(299): pocketmine\server()
#26 pmsrc(11): require(string[57] phar:///root/Server/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Nya-Enzo** [comment]
Its easy, since PocketMine API 4, $event->setCancelled() method doesnt exists anymore. You should replace it by: $event->cancel();

**Comment by AIPTU** [comment]
This issue still occurs to me.

**Comment by AIPTU** [comment]
Solved the issue by using this build https://github.com/Muqsit/InvCrashFix/commit/52901e31be4db313beb810dae0f3fad1fe92bd62
